# Generated by Django 4.2.2 on 2023-06-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommapp", "0002_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_title", models.CharField(max_length=200)),
                ("product_detail", models.TextField(null=True)),
                ("price", models.FloatField()),
            ],
        ),
    ]
