# Generated by Django 4.2.2 on 2023-06-21 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ecommapp", "0003_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product_category",
            old_name="product_detail",
            new_name="detail",
        ),
        migrations.RenameField(
            model_name="product_category",
            old_name="product_title",
            new_name="title",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecommapp.product_category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecommapp.vendor",
            ),
        ),
    ]
