# Generated by Django 4.2.2 on 2023-07-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommapp", "0007_customeraddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeraddress",
            name="default_address",
            field=models.BooleanField(default=False),
        ),
    ]
